name: docker build

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - 'master'
jobs:
  build-image:
    runs-on: ubuntu-latest
    # 定义任务中的步骤
    steps:
      # 获取提交
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 QEMU 模拟器，这通常用于多平台的 Docker 构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 Docker Buildx，用于构建多平台的 Docker 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 设置tag 提取 Docker 的元数据（标签、标签）
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            xlh001/proxy_pool

      # 登录到 Docker Hub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建并推送 Docker 镜像到 docker.io 和 ghcr.io
      - name: Build and push Docker images to docker.io
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
